config/routes.rb
Til5::Application.routes.draw do

  resources :lockers do
    member do
      get :rent, :as => :new_rent, :to => "lockers#new_rent"
      post :rent, :as => :create_rent, :to => "lockers#create_rent"
      post :restore
    end
  end

  resources :leads do
    member do
      get :survey, :as => :new_survey, :to => "leads#new_survey"
      post :survey, :as => :survey, :to => "leads#survey"
    end
  end

  resources :accounts do
    member do
      get :renew
      put :do_renew
      get :suspend
      put :do_suspend
      get :transfer
      put :do_transfer
      post :resume
      get :participate, :as => :new_participation, :to => "accounts#new_participation"
      put :participate, :as => :update_participation, :to => "accounts#update_participation"
      get :survey, :as => :new_survey, :to => "accounts#new_survey"
      post :survey, :as => :survey, :to => "accounts#survey"
      get :edit_membership_state
      put :update_membership_state
      get :new_locker
      post :create_locker
      put :create_locker
    end
    collection do
      get :options, :to => "accounts#options"
    end
    resources :contracts, :only => [:edit, :update, :show] do
      member do
        post :sign, :to => "contracts#sign"
      end
    end
  end

  resources :participations, :only => [:destroy] do
    member do
      post :attend
      get :transfer, :as => :new_lesson_transfer, :to => "participations#new_lesson_transfer"
      put :transfer, :as => :update_lesson_transfer, :to => "participations#update_lesson_transfer"
    end
  end

  match 'test' => 'home#test'

  match 'welcome' => 'welcome#index'
  match 'welcome/:id' =>'welcome#show'
  resources :contracts, :only => [:index, :create, :show] do
    member do
      post :sign, :to => "contracts#sign"
    end
    collection do
      post :preview, :to => "contracts#preview"
    end
  end

  resources :users do
    collection do
      post :redraw, :to => "users#redraw"
    end
    member do
      post :redraw, :to => "users#redraw"
      post :add_appointment, :to =>"users#add_appointment"
      put :add_appointment, :to => "users#add_appointment"
      get :new_appointment, :to => "users#new_appointment"
      get :appointments, :to => "users#appointments"
    end
    get 'appointments/:year-:month-:day', :on => :member, :action => :appointments, :as => :appointments_by_date
  end

  resources :appointments, :only => [:show, :destroy] do
    member do
      post :cancel, :to => "appointments#cancel"
    end
  end

  namespace :admin do
    resources :schedules, :only => [:index] do
      collection do
        get ':year-:month-:day', :action => :show, :as => :show
        put ':year-:month-:day', :action => :update, :as => :update
        get ':year-:month-:day/edit', :action => :edit, :as => :edit
      end
    end

    resources :membership_types, :only => [:index, :new, :edit, :update, :create, :destroy]
    resources :contract_types, :only => [:index, :new, :edit, :update, :create, :destroy] do
      resources :contract_templates, :only => [:index, :new, :create] do
      end
    end

    resources :lessons, :only => [:index, :new, :edit, :update, :create, :destroy]

    resources :lockers, :only => [:index, :destroy, :new, :create] do
    end

    resources :contract_templates do
      member do
        get :preview
      end
    end

    resources :user_ranks, :only => [:index] do
      collection do
        post :sort, :to => "user_ranks#sort", :as => "sort"
      end
    end
  end

end

app/models/contract_template.rb
require 'markdown'
module ContractTemplateDecorator
end
# template for contract,
# can take placeholders in the form of ${name:type[,param1:value]*} for farther customizing.
#
# The template itself should be written in Markdown( I dont want to build a Rich Content Editor),
# but it's not easy to express all the content with markdown, so i'm considering to enable
# using attachments as the content of the contract, and only require the user to fill all the blacks
# back.
class ContractTemplate < ActiveRecord::Base
  module Format
    MARKDOWN = "markdown"
    HTML = "html"
    AVAILABLE = [MARKDOWN, HTML]
  end
  class ValidationError < Error
  end
  class TypeValidationError < ValidationError
    attr_accessor :type
    def initialize(type)
      @type = type
    end
  end
  class ParamRequiredError < ValidationError
  end

  attr_accessible :template, :format, :contract_type
  serialize :parameters, Hash

  validates_inclusion_of :format, :in => Format::AVAILABLE
  validates_uniqueness_of :contract_type

  before_validation(:on => :create) do
    self.parse_and_refresh_parameters
  end

  before_validation(:on => :update) do
    if self.template_changed?
      self.parse_and_refresh_parameters
    end
  end

  # convert the contract to its printable form( a html) with all the placeholders are replaces by underlines
  def to_printable
    template = ContractTemplateDecorator::Parser.parse(self.template) do |name, type, params|
      type = ContractTemplateDecorator::ParamType.get_type_by_name type
      length = (params[:length] || type.default_length).to_i
      "_" * length
    end
    case self.format
      when Format::MARKDOWN
        Markdown.new(template).to_html
      when Format::HTML
        template
      else
        "Unrecognizable format: '#{self.format}'"
    end
  end

  def to_preview
    template = ContractTemplateDecorator::Parser.parse(self.template) do |name, type, params|
      type = ContractTemplateDecorator::ParamType.get_type_by_name type
      length = (params[:length] || type.default_length).to_i
      ("%-#{length * 2}s" % "(#{name})")
    end
    case self.format
      when Format::MARKDOWN
        Markdown.new(template).to_html
      when Format::HTML
        template
      else
        "Unrecognizable format: '#{self.format}'"
    end
  end

  def validate_params params
    params.symbolize_keys!
    self.parameters.each do |key, parameter|
      param = params[key]
      raise ParamRequiredError unless param || !parameter.required?
      type = ContractTemplateDecorator::ParamType.get_type_by_name parameter.type
      raise TypeValidationError.new( parameter.type) unless type && type.validate(param)
    end
  end

  def generate_contract contract
    template = ContractTemplateDecorator::Parser.parse(self.template) do |name, type, attributes|
      value = contract.respond_to?(name.to_sym) ? contract.send(name.to_sym) : nil
      unless value
        type = ContractTemplateDecorator::ParamType.get_type_by_name type
        length = (attributes[:length] || type.default_length).to_i
        value = "_" * length
      end
      value.to_s
    end
    case self.format
      when Format::MARKDOWN
        Markdown.new(template).to_html
      when Format::HTML
        template
      else
        "Unrecognizable format: '#{self.format}'"
    end
  end

  protected

  def parse_and_refresh_parameters
    parameters = ContractTemplateDecorator::Parser.parse_parameters( self.template, self.errors)
    self.parameters = parameters
  end
end
require File.join(File.dirname(__FILE__), "/contract_template_decorator/param") #to fix the yaml-dump

app/controllers/admin/contract_templates_controller.rb
class Admin::ContractTemplatesController < Admin::ApplicationController
  before_filter "set_current_tab('admin/contract_templates')", :only => [ :index, :show ]

  load_resource :contract_template
  layout false, :only => [:preview]

  skip_before_filter :require_admin_user
  before_filter "require_manager(ContractTemplate)"

  # GET /contract_types/1/contract_templates
  # AJAX
  def index
    respond_with(@contract_templates)
  end

  # GET /contract_types/1/contract_templates/new
  # AJAX
  def new
    respond_with(@contract_template)
  end

  # POST /contract_types/1/contract_templates
  # AJAX
  def create
    params[:contract_template][:format] = "html"
    @contract_template = ContractTemplate.new(params[:contract_template])
    respond_with(@contract_template) do |format|
      @contract_template.save
    end
  end

  # GET /contract_templates/1/edit
  # AJAX
  def edit
    @contract_template = ContractTemplate.find(params[:id])
  end

  # PUT /contract_templates/1
  # AJAX
  def update
    @contract_template = ContractTemplate.find(params[:id])
    respond_with(@contract_template) do |format|
      @contract_template.update_attributes(params[:contract_template])
    end
  end

  # DELETE /contract_templates/1
  # AJAX
  def destroy
  end
end

app/helpers/contract_templates_helper.rb
module ContractTemplatesHelper
  def link_to_preview( template, params = {})
    link_to(t(:preview), params[])
  end
end

app/views/admin/contract_templates/_contract_template.html.haml
%li{:id => "contract_template_#{contract_template.id}", :class => "#{contract_template_counter == 0 ? "first" : ""}"}
  .tools
    = link_to_edit(contract_template, :url => edit_admin_contract_template_path(contract_template)) << " |"
    = link_to(t(:preview), preview_admin_contract_template_path(contract_template, :format => :pdf), :target => "_blank")
  %span= t("view.contract_templates.contracts.#{contract_template.contract_type.to_s.underscore.split("/").last}")
  %span= contract_template.created_at

app/views/admin/contract_templates/_edit.html.haml
.remote
  = form_for( [:admin, @contract_template], :as =>:contract_template, :html => one_submit_only(:contract_template).merge(:class => "edit_contract_template", :id => "edit_template_#{@contract_template.id}"), :remote => true) do |f|
    = link_to_close edit_admin_contract_template_path(@contract_template)
    = f.error_messages
    = render :partial => "top_section", :locals => {:f =>f, :edit => true}
    .buttonbar
      = f.submit t(:save_contract_template), :id => :"contract_template_#{@contract_template.id}_submit"
      or
      = link_to_cancel edit_admin_contract_template_path(@contract_template)

app/views/admin/contract_templates/_form.html.haml
=form_for [:admin, @contract_template], :remote => true do |f|
  = link_to_close new_admin_contract_template_path( @contract_type)
  = f.error_messages :object_name => t("contract_templates")
  = render "admin/contract_templates/top_section", :f => f
  .buttonbar
    = f.submit t(:create_contract_template), :id => :"contract_template_submit"
    or
    = link_to_cancel new_admin_contract_template_path

app/views/admin/contract_templates/_sidebar_index.html.haml
= "Sidebar"

app/views/admin/contract_templates/_top_section.html.haml
.section
  %table
    %tr
      %td
        .label.req= t("contract_type") +":"
        = f.select :contract_type, Contract.contracts.reduce([]){|result, ele| result << [t("view.contract_templates.contracts.#{ele.to_s.underscore.split("/").last}"), ele.to_s]}
    %tr
      %td
        .label.req= t("template") + ":"
        = f.text_area :template, :id => "contract_template_template"

app/views/admin/contract_templates/index.html.haml
.title_tools
  = link_to_inline(:create_contract_template, new_admin_contract_template_path, :text => t("create_contract_template"))

.title
  %span#create_contract_template_title #{t("contract_templates")}
  = image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;")
.remote#create_contract_template{hidden}

.list#contract_templates
  - if @contract_templates.any?
    = render :partial => "admin/contract_templates/contract_template", :collection => @contract_templates
  - else
    = render "shared/empty"

app/views/admin/contract_templates/preview.html.haml
!= @contract_template.to_printable