config/routes.rb
Til5::Application.routes.draw do

  resources :lockers do
    member do
      get :rent, :as => :new_rent, :to => "lockers#new_rent"
      post :rent, :as => :create_rent, :to => "lockers#create_rent"
      post :restore
    end
  end

  resources :leads do
    member do
      get :survey, :as => :new_survey, :to => "leads#new_survey"
      post :survey, :as => :survey, :to => "leads#survey"
    end
  end

  resources :accounts do
    member do
      get :renew
      put :do_renew
      get :suspend
      put :do_suspend
      get :transfer
      put :do_transfer
      post :resume
      get :participate, :as => :new_participation, :to => "accounts#new_participation"
      put :participate, :as => :update_participation, :to => "accounts#update_participation"
      get :survey, :as => :new_survey, :to => "accounts#new_survey"
      post :survey, :as => :survey, :to => "accounts#survey"
      get :edit_membership_state
      put :update_membership_state
      get :new_locker
      post :create_locker
      put :create_locker
    end
    collection do
      get :options, :to => "accounts#options"
    end
    resources :contracts, :only => [:edit, :update, :show] do
      member do
        post :sign, :to => "contracts#sign"
      end
    end
  end

  resources :participations, :only => [:destroy] do
    member do
      post :attend
      get :transfer, :as => :new_lesson_transfer, :to => "participations#new_lesson_transfer"
      put :transfer, :as => :update_lesson_transfer, :to => "participations#update_lesson_transfer"
    end
  end

  match 'test' => 'home#test'

  match 'welcome' => 'welcome#index'
  match 'welcome/:id' =>'welcome#show'
  resources :contracts, :only => [:index, :create, :show] do
    member do
      post :sign, :to => "contracts#sign"
    end
    collection do
      post :preview, :to => "contracts#preview"
    end
  end

  resources :users do
    collection do
      post :redraw, :to => "users#redraw"
    end
    member do
      post :redraw, :to => "users#redraw"
      post :add_appointment, :to =>"users#add_appointment"
      put :add_appointment, :to => "users#add_appointment"
      get :new_appointment, :to => "users#new_appointment"
      get :appointments, :to => "users#appointments"
    end
    get 'appointments/:year-:month-:day', :on => :member, :action => :appointments, :as => :appointments_by_date
  end

  resources :appointments, :only => [:show, :destroy] do
    member do
      post :cancel, :to => "appointments#cancel"
    end
  end

  namespace :admin do
    resources :schedules, :only => [:index] do
      collection do
        get ':year-:month-:day', :action => :show, :as => :show
        put ':year-:month-:day', :action => :update, :as => :update
        get ':year-:month-:day/edit', :action => :edit, :as => :edit
      end
    end

    resources :membership_types, :only => [:index, :new, :edit, :update, :create, :destroy]
    resources :contract_types, :only => [:index, :new, :edit, :update, :create, :destroy] do
      resources :contract_templates, :only => [:index, :new, :create] do
      end
    end

    resources :lessons, :only => [:index, :new, :edit, :update, :create, :destroy]

    resources :lockers, :only => [:index, :destroy, :new, :create] do
    end

    resources :contract_templates do
      member do
        get :preview
      end
    end

    resources :user_ranks, :only => [:index] do
      collection do
        post :sort, :to => "user_ranks#sort", :as => "sort"
      end
    end
  end

end

app/controllers/admin/membership_types_controller.rb
class Admin::MembershipTypesController < Admin::ApplicationController
  before_filter "set_current_tab('admin/membership_types')", :only => [ :index, :show ]
  skip_before_filter :require_admin_user
  before_filter "require_manager(MembershipType)"

  load_resource

  def create
    @membership_type = MembershipType.new(params[:membership_type])

    respond_with(@membership_type) do |format|
      @membership_type.save
    end
  end
  def update
    @membership_type = MembershipType.find(params[:id])
    respond_with(@membership_type) do |format|
      @membership_type.update_attributes(params[:membership_type])
    end
  end
  def destroy
    @membership_type = MembershipType.find(params[:id])
    @membership_type.destroy
    respond_with(@membership_type)
  end
end

app/helpers/admin/membership_types_helper.rb
module Admin::MembershipTypesHelper
end

app/views/admin/membership_types/_edit.html.haml
.remote
  = form_for([:admin, @membership_type], :as => :membership_type, :html => one_submit_only(:membership_type), :remote => true) do |f|
    = link_to_close edit_admin_membership_type_path(@membership_type)
    = f.error_messages
    = render :partial => "top_section", :locals => {:f => f, :edit => true}
    .buttonbar
      = f.submit t(:save_membership_type), :id => :membership_type_submit
      or
      = link_to_cancel edit_admin_membership_type_path(@membership_type)

app/views/admin/membership_types/_form.html.haml
= form_for [:admin, @membership_type], :html => one_submit_only(:membership_type), :remote => true do |f|
  = link_to_close new_admin_membership_type_path
  = f.error_messages :object_name => t(:membership_types)
  = render "admin/membership_types/top_section", :f => f
  .buttonbar
    = f.submit t(:create_membership_type), :id => :membership_type_submit
    or
    = link_to_cancel new_admin_membership_type_path

app/views/admin/membership_types/_membership_type.html.haml
%li[membership_type]
  .tools
    = link_to_edit(membership_type, :url => edit_admin_membership_type_path(membership_type)) << " |"
    - if membership_type.memberships.count <= 0
      = link_to_delete(membership_type, :url => url_for([:admin, membership_type]))
    - else
      %span{:style => "color: #777"} #{t(:delete)}!
  .membership_info
    %span.black= membership_type.name
    %tt
      %span.black= "|"
      = t(:duration) + ": " + membership_type.duration.to_s
    %dt
      = t(:transferable) + ": " + membership_type.transferable.to_s
      %span.black="|"
      = t(:suspendable) + ": " + membership_type.suspendable.to_s
      %span.black="|"
      = t(:terminatable) + ":" + membership_type.terminatable.to_s

app/views/admin/membership_types/_top_section.html.haml
.section
  %table
    %tr
      %td
        .label.top.req= t(:name) + ":"
        = f.text_field :name
      %td
        .label.top.req= t(:price) + ":"
        = f.text_field :price
    %tr
      %td
        .label.req= t(:duration) + "(" + t(:days) + "):"
        = f.text_field(:duration)
    %tr
      %td
        .label.req= t(:transferable) + ":"
        = f.check_box(:transferable)
    %tr
      %td
        .label.req= t(:suspendable) + ":"
        = f.check_box(:suspendable)
    %tr
      %td
        .label.req= t(:terminatable) + ":"
        = f.check_box(:terminatable)

app/views/admin/membership_types/index.html.haml
.title_tools
  =link_to_inline( :create_membership_type, new_admin_membership_type_path, :text => t(:create_membership_type))

.title
  %span#create_membership_type_title= t(:membership_types)
  = image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;")
  .remote#create_membership_type{ hidden}

.list#membership_types
  - if @membership_types.any?
    = render :partial => "admin/membership_types/membership_type", :collection => @membership_types
  - else
    = render "shared/empty"