config/routes.rb
Til5::Application.routes.draw do

  resources :lockers do
    member do
      get :rent, :as => :new_rent, :to => "lockers#new_rent"
      post :rent, :as => :create_rent, :to => "lockers#create_rent"
      post :restore
    end
  end

  resources :leads do
    member do
      get :survey, :as => :new_survey, :to => "leads#new_survey"
      post :survey, :as => :survey, :to => "leads#survey"
    end
  end

  resources :accounts do
    member do
      get :renew
      put :do_renew
      get :suspend
      put :do_suspend
      get :transfer
      put :do_transfer
      post :resume
      get :participate, :as => :new_participation, :to => "accounts#new_participation"
      put :participate, :as => :update_participation, :to => "accounts#update_participation"
      get :survey, :as => :new_survey, :to => "accounts#new_survey"
      post :survey, :as => :survey, :to => "accounts#survey"
      get :edit_membership_state
      put :update_membership_state
      get :new_locker
      post :create_locker
      put :create_locker
    end
    collection do
      get :options, :to => "accounts#options"
    end
    resources :contracts, :only => [:edit, :update, :show] do
      member do
        post :sign, :to => "contracts#sign"
      end
    end
  end

  resources :participations, :only => [:destroy] do
    member do
      post :attend
      get :transfer, :as => :new_lesson_transfer, :to => "participations#new_lesson_transfer"
      put :transfer, :as => :update_lesson_transfer, :to => "participations#update_lesson_transfer"
    end
  end

  match 'test' => 'home#test'

  match 'welcome' => 'welcome#index'
  match 'welcome/:id' =>'welcome#show'
  resources :contracts, :only => [:index, :create, :show] do
    member do
      post :sign, :to => "contracts#sign"
    end
    collection do
      post :preview, :to => "contracts#preview"
    end
  end

  resources :users do
    collection do
      post :redraw, :to => "users#redraw"
    end
    member do
      post :redraw, :to => "users#redraw"
      post :add_appointment, :to =>"users#add_appointment"
      put :add_appointment, :to => "users#add_appointment"
      get :new_appointment, :to => "users#new_appointment"
      get :appointments, :to => "users#appointments"
    end
    get 'appointments/:year-:month-:day', :on => :member, :action => :appointments, :as => :appointments_by_date
  end

  resources :appointments, :only => [:show, :destroy] do
    member do
      post :cancel, :to => "appointments#cancel"
    end
  end

  namespace :admin do
    resources :schedules, :only => [:index] do
      collection do
        get ':year-:month-:day', :action => :show, :as => :show
        put ':year-:month-:day', :action => :update, :as => :update
        get ':year-:month-:day/edit', :action => :edit, :as => :edit
      end
    end

    resources :membership_types, :only => [:index, :new, :edit, :update, :create, :destroy]
    resources :contract_types, :only => [:index, :new, :edit, :update, :create, :destroy] do
      resources :contract_templates, :only => [:index, :new, :create] do
      end
    end

    resources :lessons, :only => [:index, :new, :edit, :update, :create, :destroy]

    resources :lockers, :only => [:index, :destroy, :new, :create] do
    end

    resources :contract_templates do
      member do
        get :preview
      end
    end

    resources :user_ranks, :only => [:index] do
      collection do
        post :sort, :to => "user_ranks#sort", :as => "sort"
      end
    end
  end

end

app/views/admin/contract_types/_contract_type.html.haml
- contract_templates_size = contract_type.contract_templates.size
%li[contract_type]
  .tools
    = link_to_edit(contract_type, :url => edit_admin_contract_type_path(contract_type)) << " |"
    - if contract_templates_size > 0
    - else
      = link_to_delete(contract_type, :url => url_for([:admin, contract_type]))

  .contract_info
    %span.black= contract_type.name
    \-
    %tt= contract_type.description

  .bottom_tools
    = link_to_inline(:"create_contract_type_#{contract_type.id}_contract_template", new_admin_contract_type_contract_template_path(contract_type), :text => t(:add_template))
  .remote{hidden.merge(:id => "create_contract_type_#{contract_type.id}_contract_template") }
  %ul.sub_list.contract-templates{:id => "contract_type_#{contract_type.id}_contract_templates"}
    = render :partial => "admin/contract_templates/contract_template", :collection => contract_type.contract_templates.order("created_at DESC")

app/views/admin/contract_types/_edit.html.haml
.remote
  = form_for([:admin, @contract_type], :as => :contract_type, :html => one_submit_only(:contract_type).merge(:class => "edit_contract_type", :id => "edit_contract_type_#{@contract_type.id}"), :remote => true) do |f|
    = link_to_close edit_admin_contract_type_path(@contract_type)
    = f.error_messages
    = render :partial => "top_section", :locals => {:f => f, :edit => true}
    .buttonbar
      = f.submit t(:save_contract_type), :id =>:contract_type_submit
      or
      = link_to_cancel edit_admin_contract_type_path(@contract_type)

app/views/admin/contract_types/_form.html.haml
= form_for [:admin, @contract_type], :html => one_submit_only(:contract_type), :remote => true do |f|
  = link_to_close new_admin_contract_type_path
  = f.error_messages :object_name => t(:contract_types)
  = render "admin/contract_types/top_section", :f => f
  .buttonbar
    = f.submit t(:create_contract_type), :id => :contract_type_submit
    or
    = link_to_cancel new_admin_contract_type_path

app/views/admin/contract_types/_top_section.html.haml
.section
  %table
    %tr
      %td
        .label.top.req= t(:name) + ":"
        = f.text_field :name
    %tr
      %td
        .label.req= t(:description) + ":"
        = f.text_field :description

app/views/admin/contract_types/index.html.haml
- content_for :stylesheet_links do
  = stylesheet_link_tag "admin/contract_types"


.title_tools
  =link_to_inline(:create_contract_type, new_admin_contract_type_path, :text => t(:create_contract_type))

.title
  %span#create_contract_type_title #{t :contract_types}
  = image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;")
.remote#create_contract_type{ hidden }

.list#contract_types
  - if @contract_types.any?
    = render :partial => "admin/contract_types/contract_type", :collection => @contract_types
  - else
    = render "shared/empty"