config/routes.rb
Til5::Application.routes.draw do

  resources :lockers do
    member do
      get :rent, :as => :new_rent, :to => "lockers#new_rent"
      post :rent, :as => :create_rent, :to => "lockers#create_rent"
      post :restore
    end
  end

  resources :leads do
    member do
      get :survey, :as => :new_survey, :to => "leads#new_survey"
      post :survey, :as => :survey, :to => "leads#survey"
    end
  end

  resources :accounts do
    member do
      get :renew
      put :do_renew
      get :suspend
      put :do_suspend
      get :transfer
      put :do_transfer
      post :resume
      get :participate, :as => :new_participation, :to => "accounts#new_participation"
      put :participate, :as => :update_participation, :to => "accounts#update_participation"
      get :survey, :as => :new_survey, :to => "accounts#new_survey"
      post :survey, :as => :survey, :to => "accounts#survey"
      get :edit_membership_state
      put :update_membership_state
      get :new_locker
      post :create_locker
      put :create_locker
    end
    collection do
      get :options, :to => "accounts#options"
    end
    resources :contracts, :only => [:edit, :update, :show] do
      member do
        post :sign, :to => "contracts#sign"
      end
    end
  end

  resources :participations, :only => [:destroy] do
    member do
      post :attend
      get :transfer, :as => :new_lesson_transfer, :to => "participations#new_lesson_transfer"
      put :transfer, :as => :update_lesson_transfer, :to => "participations#update_lesson_transfer"
    end
  end

  match 'test' => 'home#test'

  match 'welcome' => 'welcome#index'
  match 'welcome/:id' =>'welcome#show'
  resources :contracts, :only => [:index, :create, :show] do
    member do
      post :sign, :to => "contracts#sign"
    end
    collection do
      post :preview, :to => "contracts#preview"
    end
  end

  resources :users do
    collection do
      post :redraw, :to => "users#redraw"
    end
    member do
      post :redraw, :to => "users#redraw"
      post :add_appointment, :to =>"users#add_appointment"
      put :add_appointment, :to => "users#add_appointment"
      get :new_appointment, :to => "users#new_appointment"
      get :appointments, :to => "users#appointments"
    end
    get 'appointments/:year-:month-:day', :on => :member, :action => :appointments, :as => :appointments_by_date
  end

  resources :appointments, :only => [:show, :destroy] do
    member do
      post :cancel, :to => "appointments#cancel"
    end
  end

  namespace :admin do
    resources :schedules, :only => [:index] do
      collection do
        get ':year-:month-:day', :action => :show, :as => :show
        put ':year-:month-:day', :action => :update, :as => :update
        get ':year-:month-:day/edit', :action => :edit, :as => :edit
      end
    end

    resources :membership_types, :only => [:index, :new, :edit, :update, :create, :destroy]
    resources :contract_types, :only => [:index, :new, :edit, :update, :create, :destroy] do
      resources :contract_templates, :only => [:index, :new, :create] do
      end
    end

    resources :lessons, :only => [:index, :new, :edit, :update, :create, :destroy]

    resources :lockers, :only => [:index, :destroy, :new, :create] do
    end

    resources :contract_templates do
      member do
        get :preview
      end
    end

    resources :user_ranks, :only => [:index] do
      collection do
        post :sort, :to => "user_ranks#sort", :as => "sort"
      end
    end
  end

end

app/views/admin/users/_profile.html.haml
- edit ||= false
.section
  %table
    %tr
      %td
        .label.top.req #{t :username}:
        = f.text_field :username
      %td= spacer
      %td
        .label.top.req #{t :email}:
        = f.text_field :email
    %tr
      %td
        .label #{t :password}:
        = f.password_field :password
      %td= spacer
      %td
        .label #{t :password_confirmation}:
        = f.password_field :password_confirmation
    %tr
      %td
        .label #{t :card_number}
        = f.text_field :card_number
    %tr
      %td(colspan=3)
        .check_box(style="margin-top:6px")
          -# Sorry, you can't revoke Admin rights from yourself.
          - User.valid_roles.each do |role|
            - if can? :manage, role
              = check_box_tag :user_roles, role, @user.is?(role), :name => "user_roles[]",
                :disabled => edit &&  @user == @current_user && cannot?(:self_assign_role, role)
              = f.label "user_roles[]", t(:"roles.#{role}")
.subtitle #{t :personal_information}
.section
  %table
    %tr
      %td
        .label #{t :first_name}:
        = f.text_field :first_name
      %td= spacer
      %td
        .label #{t :last_name}:
        = f.text_field :last_name
    %tr
      %td
        .label #{t :mobile}:
        = f.text_field :mobile

app/views/admin/users/_user.html.haml
%li.highlight[user]

  - if user.awaits_approval?
    .strip.signed_up #{t :user_signed_up}
  - elsif user.suspended?
    .strip.suspended #{t :user_suspended}
  - elsif user.admin?
    .strip.admin #{t :user_admin}
  - else
    .strip.active #{t :user_active}

  = avatar_for(user, :size => :medium, :width => 30, :height => 30 )

  .indentfull
    .tools
      - if can?(:edit, user)
        = link_to_edit(user, :url => edit_admin_user_path(user)) << " | "
      - else
        = "<font color='silver'>#{t :edit}!</font> | ".html_safe

      - if user.suspended?
        - if can?(:reactivate, user)
          = link_to_reactivate(user) << " | "
        - else
          = "<font color='silver'>#{user.awaits_approval? ? t(:approve) : t(:reactivate)}</font> | ".html_safe
      - elsif user != @current_user && can?(:suspend, user)
        = link_to_suspend(user) << " | "
      - else
        = "<font color='silver'>#{t :suspend}!</font> | ".html_safe

    %span.black #{link_to(h(user.full_name), user)} (#{user.username})
    %tt
      = "- #{h(user.title)}" unless user.title.blank?
      = " " + t(:at) + " " + h(user.company) unless user.company.blank?

      %span.black= "|"
      - if user.last_request_at && user.login_count > 0
        = t('pluralize.login', user.login_count)
        %span.black= "|"

      - if user.roles.size > 0
        = user.roles.map do |role| t(:"roles.#{role}") end.join(", ")
        %span.black= "|"

      - if user.awaits_approval?
        %b.cool #{t :user_awaits_approval}
      - elsif user.last_request_at
        %span.cool #{t(:last_seen, time_ago_in_words(user.last_request_at))}
      - else
        %span.warn #{t :user_never_logged_in}
    %dt{ :style => "padding: 2px 0px 0px 0px" }
      = link_to_email(user.email.to_s) << " | "
      = "#{t :phone_small}: <b>".html_safe + user.phone << "</b> | ".html_safe if user.phone?
      = "#{t :mobile_small}: <b>".html_safe + user.mobile << "</b> | ".html_safe if user.mobile?

      - if !user.suspended?
        %span #{t(:user_since, l(user.created_at.to_date, :format => :mmddyy))}
      - elsif user.awaits_approval?
        %b.cool #{t(:user_signed_up_on, l(user.created_at, :format => :mmddhhss))}
      - else
        %span.warn #{t(:user_suspended_on, l(user.created_at.to_date, :format => :mmddyy))}

app/views/admin/users/index.html.haml
= styles_for :user

= content_for :after_head do
  = include_card_widget
.title_tools
  = link_to_inline(:create_user, new_admin_user_path, :text => t(:create_user))

.title
  %span#create_user_title #{t :users}
  = image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;")
.remote#create_user{ hidden }

.list#users= render :partial => "admin/users/user", :collection => @users
#paginate= render "shared/paginate"
#export= render "shared/export"